#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v2
# autospec commit: 250a666
#
Name     : libtermkey
Version  : 0.22
Release  : 5
URL      : https://github.com/neovim/libtermkey/archive/v0.22/libtermkey-0.22.tar.gz
Source0  : https://github.com/neovim/libtermkey/archive/v0.22/libtermkey-0.22.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libtermkey-lib = %{version}-%{release}
Requires: libtermkey-license = %{version}-%{release}
Requires: libtermkey-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the libtermkey package.
Group: Development
Requires: libtermkey-lib = %{version}-%{release}
Provides: libtermkey-devel = %{version}-%{release}
Requires: libtermkey = %{version}-%{release}

%description dev
dev components for the libtermkey package.


%package lib
Summary: lib components for the libtermkey package.
Group: Libraries
Requires: libtermkey-license = %{version}-%{release}

%description lib
lib components for the libtermkey package.


%package license
Summary: license components for the libtermkey package.
Group: Default

%description license
license components for the libtermkey package.


%package man
Summary: man components for the libtermkey package.
Group: Default

%description man
man components for the libtermkey package.


%prep
%setup -q -n libtermkey-0.22
cd %{_builddir}/libtermkey-0.22

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1699482598
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}  PREFIX=/usr LIBDIR=/usr/lib64


%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1699482598
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libtermkey
cp %{_builddir}/libtermkey-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libtermkey/a002aff6411e4d72243adf719592954419a51f47 || :
%make_install PREFIX=/usr LIBDIR=/usr/lib64

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/termkey.h
/usr/lib64/libtermkey.so
/usr/lib64/pkgconfig/termkey.pc
/usr/share/man/man3/termkey_advisereadable.3.gz
/usr/share/man/man3/termkey_canonicalise.3.gz
/usr/share/man/man3/termkey_get_buffer_remaining.3.gz
/usr/share/man/man3/termkey_get_fd.3.gz
/usr/share/man/man3/termkey_get_keyname.3.gz
/usr/share/man/man3/termkey_getkey.3.gz
/usr/share/man/man3/termkey_interpret_csi.3.gz
/usr/share/man/man3/termkey_interpret_modereport.3.gz
/usr/share/man/man3/termkey_interpret_mouse.3.gz
/usr/share/man/man3/termkey_interpret_position.3.gz
/usr/share/man/man3/termkey_interpret_string.3.gz
/usr/share/man/man3/termkey_keycmp.3.gz
/usr/share/man/man3/termkey_keyname2sym.3.gz
/usr/share/man/man3/termkey_lookup_keyname.3.gz
/usr/share/man/man3/termkey_new.3.gz
/usr/share/man/man3/termkey_push_bytes.3.gz
/usr/share/man/man3/termkey_set_buffer_size.3.gz
/usr/share/man/man3/termkey_set_canonflags.3.gz
/usr/share/man/man3/termkey_set_flags.3.gz
/usr/share/man/man3/termkey_set_waittime.3.gz
/usr/share/man/man3/termkey_start.3.gz
/usr/share/man/man3/termkey_strfkey.3.gz
/usr/share/man/man3/termkey_strpkey.3.gz
/usr/share/man/man3/termkey_waitkey.3.gz

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtermkey.so.1
/usr/lib64/libtermkey.so.1.14.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libtermkey/a002aff6411e4d72243adf719592954419a51f47

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/termkey.7.gz
